#! /bin/sh

### AUTOSTART ###
$HOME/.local/bin/autostart.sh &

### MONITOR(S) ###
bspc monitor -d I II III IV V

### BSPWM CONFIGS ###
bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focused_border_color "#7FB4CA"
bspc config normal_border_color "#1F1F28"
bspc config presel_border_color "#294172"
bspc config urgent_border_color "#C34043"

# this is to fix the weird gap between bspwm and polybar
# since polybar have reserved 4 pixel struts
bspc config ignore_ewmh_struts 	 true
bspc config top_padding 		 54

### RULES ###
bspc rule -a firefox desktop='^1' focus=on
bspc rule -a discord desktop='^2'
bspc rule -a kitty desktop='^3'
bspc rule -a dolphin desktop='^4'
bspc rule -a Emacs state=tiled
bspc rule -a Sxiv state=floating
bspc rule -a imv state=floating
bspc rule -a mpv state=floating
