#! /bin/sh

### AUTOSTART ###
$HOME/.config/polybar/launch.sh
$HOME/.fehbg
$HOME/.local/bin/check-battery &
pgrep -x dunst > /dev/null || dunst &
pgrep -x greenclip daemon > /dev/null || greenclip daemon &
pgrep -x sxhkd > /dev/null || sxhkd &
picom -fc &

### MONITOR(S) ###
bspc monitor -d I II III IV V

### BSPWM CONFIGS ###
bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focused_border_color "#7FB4CA"
bspc config normal_border_color "#1F1F28"
bspc config presel_border_color "#294172"
bspc config urgent_border_color "#C34043"

# this is to fix the weird gap between bspwm and polybar
# since polybar have reserved 4 pixel struts
bspc config ignore_ewmh_struts 	 true
bspc config top_padding 		 39

### RULES ###
bspc rule -a firefox desktop='^1' focus=on
bspc rule -a Discord desktop='^2'
