#! /bin/sh

### AUTOSTART ###
$HOME/.fehbg
$HOME/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &
picom -fc &
dunst &
$HOME/.local/bin/check-battery &
greenclip daemon &

### MONITOR(S) ###
bspc monitor -d I II III IV V

### BSPWM CONFIGS ###
bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

#bspc config normal_border_color "#484848"
bspc config focused_border_color "#7FB4CA"
#bspc config urgent_border_color "#C34043"
# bspc config presel_border_color "#26E2FF"

# this is to fix the weird gap between bspwm and polybar
# since polybar have reserved 4 pixel struts
bspc config ignore_ewmh_struts 	 true
bspc config top_padding 		 39

### RULES ###
bspc rule -a firefox desktop='^1' focus=on
bspc rule -a Discord desktop='^2'
