#!/bin/sh

alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
alias ls='lsd'
alias la='ls -a'
alias lla='ls -la'
alias lt='lsd --ignore-glob .git --tree '

alias v='nvim'
alias sb='feh --bg-fill'
alias sxiv='sxiv -b'
alias lf='lfrun'
