live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x1F1F28"
foreground = "0xDCD7BA"

[colors.normal]
black = "0x090618"
red = "0xC34043"
green = "0x76946A"
yellow = "0xC0A36E"
blue = "0x7E9CD8"
magenta = "0x957FB8"
cyan = "0x6A9589"
white = "0xC8C093"

[colors.bright]
black = "0x727169"
red = "0xE82424"
green = "0x98BB6C"
yellow = "0xE6C384"
blue = "0x7FB4CA"
magenta = "0x938AA9"
cyan = "0x7AA89F"
white = "0xDCD7BA"

[colors.selection]
background = "0x2D4F67"
foreground = "0xC8C093"

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "on"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[scrolling]
history = 10000
multiplier = 10

[window]
decorations = "Full"
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 105
lines = 30

[window.padding]
x = 10
y = 10

[window.position]
x = 350
y = 150
