# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """$username$hostname$directory$fill$all$line_break$cmd_duration$character"""
command_timeout = 1_000

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜](bold red)"

[username]
show_always = true
style_user = "red"
style_root = "blue"
format =  "[\\[](blue)[$user]($style)[@](bold yellow)"

[hostname]
ssh_only = false
style = "white"
format =  "[$hostname]($style) "

[directory]
truncation_length = 5
style = "green"
read_only = " "
format = "[$read_only]($read_only_style)[$path]($style)[\\]](bold blue) "

[git_branch]
symbol = "[](bold yellow) "

[cmd_duration]
# only start printing the took time when a command take longer than 3 seconds
min_time = 3_000

# create a gap to make left prompt and "right prompt" in one line
[fill]
symbol = " "

[aws]
symbol = "[ ](bold white)"

[battery]
disabled = true

[python]
symbol = "[ ](bold green)"

[lua]
symbol = "[ ](bold purple)"

